#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pinniped-config-controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pinniped-config-controller-manager
rules:
  - apiGroups: [""]
    resources: [secrets, configmaps]
    verbs: [create, get, list, patch, update, watch, delete]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pinniped-config-controller-manager
subjects:
  - kind: ServiceAccount
    name: pinniped-config-controller-manager
roleRef:
  kind: Role
  name: pinniped-config-controller-manager
  apiGroup: rbac.authorization.k8s.io
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pinniped-config-controller-manager
spec:
  selector:
    matchLabels:
      app: pinniped-config-controller-manager
  template:
    metadata:
      labels:
        app: pinniped-config-controller-manager
    spec:
      serviceAccountName: pinniped-config-controller-manager
      containers:
      - image: #@ data.values.image
        name: pinniped-config-controller-manager
